### ISSUE TITLE
Is this open source?

### ISSUE THREAD

**Issue by swagat-dash** [madclem/madclem.github.io#1]
I really loved this site and told about it to all my friends. I want to know that this is opensource or not, as I need the source code. I tried downloading it from github as a zip file, but It did not worked.

**Comment by madclem** [comment]
Sorry for the late (late, late!) reply, the source code for this experiment was compiled for optimisations purposes. Let me know if I can help you with the logic or anything!

Edit: And thank you very much for the kind words, much appreciated!

**Comment by swagat-dash** [comment]
How to run it? 
When I tried running, it just shows black screen
